/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as HumanRouteImport } from './routes/human'
import { Route as NonhumanRouteImport } from './routes/nonhuman'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyChoicesRouteImport } from './routes/privacy-choices'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiHumanAiRouteImport } from './routes/api/human-ai'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as HumanIndexRouteImport } from './routes/human.index'
import { Route as HumanAndroidRouteImport } from './routes/human.android'
import { Route as HumanDeployRouteImport } from './routes/human.deploy'
import { Route as HumanSetupRouteImport } from './routes/human.setup'
import { Route as HumanStudioRouteImport } from './routes/human.studio'
import { Route as HumanWalletRouteImport } from './routes/human.wallet'
import { Route as NonhumanIndexRouteImport } from './routes/nonhuman.index'
import { Route as NonhumanApiRouteImport } from './routes/nonhuman.api'
import { Route as NonhumanChainsRouteImport } from './routes/nonhuman.chains'
import { Route as NonhumanDashboardRouteImport } from './routes/nonhuman.dashboard'
import { Route as NonhumanMcpRouteImport } from './routes/nonhuman.mcp'
import { Route as NonhumanPayPerCallRouteImport } from './routes/nonhuman.pay-per-call'
import { Route as NonhumanPricingRouteImport } from './routes/nonhuman.pricing'
import { Route as NonhumanWalletsRouteImport } from './routes/nonhuman.wallets'
import { Route as ApiPublicOpenapiRouteImport } from './routes/api/public/openapi'
import { Route as ApiPublicMachineSplatRouteImport } from './routes/api/public/machine/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanRoute = HumanRouteImport.update({
  id: '/human',
  path: '/human',
  getParentRoute: () => rootRouteImport,
} as any)
const NonhumanRoute = NonhumanRouteImport.update({
  id: '/nonhuman',
  path: '/nonhuman',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyChoicesRoute = PrivacyChoicesRouteImport.update({
  id: '/privacy-choices',
  path: '/privacy-choices',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHumanAiRoute = ApiHumanAiRouteImport.update({
  id: '/api/human-ai',
  path: '/api/human-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanIndexRoute = HumanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HumanRoute,
} as any)
const HumanAndroidRoute = HumanAndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => HumanRoute,
} as any)
const HumanDeployRoute = HumanDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => HumanRoute,
} as any)
const HumanSetupRoute = HumanSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => HumanRoute,
} as any)
const HumanStudioRoute = HumanStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => HumanRoute,
} as any)
const HumanWalletRoute = HumanWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => HumanRoute,
} as any)
const NonhumanIndexRoute = NonhumanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NonhumanRoute,
} as any)
const NonhumanApiRoute = NonhumanApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => NonhumanRoute,
} as any)
const NonhumanChainsRoute = NonhumanChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => NonhumanRoute,
} as any)
const NonhumanDashboardRoute = NonhumanDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NonhumanRoute,
} as any)
const NonhumanMcpRoute = NonhumanMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => NonhumanRoute,
} as any)
const NonhumanPayPerCallRoute = NonhumanPayPerCallRouteImport.update({
  id: '/pay-per-call',
  path: '/pay-per-call',
  getParentRoute: () => NonhumanRoute,
} as any)
const NonhumanPricingRoute = NonhumanPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => NonhumanRoute,
} as any)
const NonhumanWalletsRoute = NonhumanWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => NonhumanRoute,
} as any)
const ApiPublicOpenapiRoute = ApiPublicOpenapiRouteImport.update({
  id: '/api/public/openapi',
  path: '/api/public/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMachineSplatRoute = ApiPublicMachineSplatRouteImport.update({
  id: '/api/public/machine/$',
  path: '/api/public/machine/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertising': typeof AdvertisingRoute
  '/human': typeof HumanRouteWithChildren
  '/nonhuman': typeof NonhumanRouteWithChildren
  '/owner': typeof OwnerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-choices': typeof PrivacyChoicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/human-ai': typeof ApiHumanAiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/human/android': typeof HumanAndroidRoute
  '/human/deploy': typeof HumanDeployRoute
  '/human/setup': typeof HumanSetupRoute
  '/human/studio': typeof HumanStudioRoute
  '/human/wallet': typeof HumanWalletRoute
  '/nonhuman/api': typeof NonhumanApiRoute
  '/nonhuman/chains': typeof NonhumanChainsRoute
  '/nonhuman/dashboard': typeof NonhumanDashboardRoute
  '/nonhuman/mcp': typeof NonhumanMcpRoute
  '/nonhuman/pay-per-call': typeof NonhumanPayPerCallRoute
  '/nonhuman/pricing': typeof NonhumanPricingRoute
  '/nonhuman/wallets': typeof NonhumanWalletsRoute
  '/blog/': typeof BlogIndexRoute
  '/human/': typeof HumanIndexRoute
  '/nonhuman/': typeof NonhumanIndexRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/public/machine/$': typeof ApiPublicMachineSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertising': typeof AdvertisingRoute
  '/owner': typeof OwnerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-choices': typeof PrivacyChoicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/human-ai': typeof ApiHumanAiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/human/android': typeof HumanAndroidRoute
  '/human/deploy': typeof HumanDeployRoute
  '/human/setup': typeof HumanSetupRoute
  '/human/studio': typeof HumanStudioRoute
  '/human/wallet': typeof HumanWalletRoute
  '/nonhuman/api': typeof NonhumanApiRoute
  '/nonhuman/chains': typeof NonhumanChainsRoute
  '/nonhuman/dashboard': typeof NonhumanDashboardRoute
  '/nonhuman/mcp': typeof NonhumanMcpRoute
  '/nonhuman/pay-per-call': typeof NonhumanPayPerCallRoute
  '/nonhuman/pricing': typeof NonhumanPricingRoute
  '/nonhuman/wallets': typeof NonhumanWalletsRoute
  '/blog': typeof BlogIndexRoute
  '/human': typeof HumanIndexRoute
  '/nonhuman': typeof NonhumanIndexRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/public/machine/$': typeof ApiPublicMachineSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertising': typeof AdvertisingRoute
  '/human': typeof HumanRouteWithChildren
  '/nonhuman': typeof NonhumanRouteWithChildren
  '/owner': typeof OwnerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-choices': typeof PrivacyChoicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/human-ai': typeof ApiHumanAiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/human/android': typeof HumanAndroidRoute
  '/human/deploy': typeof HumanDeployRoute
  '/human/setup': typeof HumanSetupRoute
  '/human/studio': typeof HumanStudioRoute
  '/human/wallet': typeof HumanWalletRoute
  '/nonhuman/api': typeof NonhumanApiRoute
  '/nonhuman/chains': typeof NonhumanChainsRoute
  '/nonhuman/dashboard': typeof NonhumanDashboardRoute
  '/nonhuman/mcp': typeof NonhumanMcpRoute
  '/nonhuman/pay-per-call': typeof NonhumanPayPerCallRoute
  '/nonhuman/pricing': typeof NonhumanPricingRoute
  '/nonhuman/wallets': typeof NonhumanWalletsRoute
  '/blog/': typeof BlogIndexRoute
  '/human/': typeof HumanIndexRoute
  '/nonhuman/': typeof NonhumanIndexRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/public/machine/$': typeof ApiPublicMachineSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertising'
    | '/human'
    | '/nonhuman'
    | '/owner'
    | '/privacy'
    | '/privacy-choices'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/api/human-ai'
    | '/blog/$slug'
    | '/human/android'
    | '/human/deploy'
    | '/human/setup'
    | '/human/studio'
    | '/human/wallet'
    | '/nonhuman/api'
    | '/nonhuman/chains'
    | '/nonhuman/dashboard'
    | '/nonhuman/mcp'
    | '/nonhuman/pay-per-call'
    | '/nonhuman/pricing'
    | '/nonhuman/wallets'
    | '/blog/'
    | '/human/'
    | '/nonhuman/'
    | '/api/public/openapi'
    | '/api/public/machine/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertising'
    | '/owner'
    | '/privacy'
    | '/privacy-choices'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/api/human-ai'
    | '/blog/$slug'
    | '/human/android'
    | '/human/deploy'
    | '/human/setup'
    | '/human/studio'
    | '/human/wallet'
    | '/nonhuman/api'
    | '/nonhuman/chains'
    | '/nonhuman/dashboard'
    | '/nonhuman/mcp'
    | '/nonhuman/pay-per-call'
    | '/nonhuman/pricing'
    | '/nonhuman/wallets'
    | '/blog'
    | '/human'
    | '/nonhuman'
    | '/api/public/openapi'
    | '/api/public/machine/$'
  id:
    | '__root__'
    | '/'
    | '/advertising'
    | '/human'
    | '/nonhuman'
    | '/owner'
    | '/privacy'
    | '/privacy-choices'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/api/human-ai'
    | '/blog/$slug'
    | '/human/android'
    | '/human/deploy'
    | '/human/setup'
    | '/human/studio'
    | '/human/wallet'
    | '/nonhuman/api'
    | '/nonhuman/chains'
    | '/nonhuman/dashboard'
    | '/nonhuman/mcp'
    | '/nonhuman/pay-per-call'
    | '/nonhuman/pricing'
    | '/nonhuman/wallets'
    | '/blog/'
    | '/human/'
    | '/nonhuman/'
    | '/api/public/openapi'
    | '/api/public/machine/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertisingRoute: typeof AdvertisingRoute
  HumanRoute: typeof HumanRouteWithChildren
  NonhumanRoute: typeof NonhumanRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyChoicesRoute: typeof PrivacyChoicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiHumanAiRoute: typeof ApiHumanAiRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicOpenapiRoute: typeof ApiPublicOpenapiRoute
  ApiPublicMachineSplatRoute: typeof ApiPublicMachineSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human': {
      id: '/human'
      path: '/human'
      fullPath: '/human'
      preLoaderRoute: typeof HumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nonhuman': {
      id: '/nonhuman'
      path: '/nonhuman'
      fullPath: '/nonhuman'
      preLoaderRoute: typeof NonhumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-choices': {
      id: '/privacy-choices'
      path: '/privacy-choices'
      fullPath: '/privacy-choices'
      preLoaderRoute: typeof PrivacyChoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/human-ai': {
      id: '/api/human-ai'
      path: '/api/human-ai'
      fullPath: '/api/human-ai'
      preLoaderRoute: typeof ApiHumanAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human/': {
      id: '/human/'
      path: '/'
      fullPath: '/human/'
      preLoaderRoute: typeof HumanIndexRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/android': {
      id: '/human/android'
      path: '/android'
      fullPath: '/human/android'
      preLoaderRoute: typeof HumanAndroidRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/deploy': {
      id: '/human/deploy'
      path: '/deploy'
      fullPath: '/human/deploy'
      preLoaderRoute: typeof HumanDeployRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/setup': {
      id: '/human/setup'
      path: '/setup'
      fullPath: '/human/setup'
      preLoaderRoute: typeof HumanSetupRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/studio': {
      id: '/human/studio'
      path: '/studio'
      fullPath: '/human/studio'
      preLoaderRoute: typeof HumanStudioRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/wallet': {
      id: '/human/wallet'
      path: '/wallet'
      fullPath: '/human/wallet'
      preLoaderRoute: typeof HumanWalletRouteImport
      parentRoute: typeof HumanRoute
    }
    '/nonhuman/': {
      id: '/nonhuman/'
      path: '/'
      fullPath: '/nonhuman/'
      preLoaderRoute: typeof NonhumanIndexRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/nonhuman/api': {
      id: '/nonhuman/api'
      path: '/api'
      fullPath: '/nonhuman/api'
      preLoaderRoute: typeof NonhumanApiRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/nonhuman/chains': {
      id: '/nonhuman/chains'
      path: '/chains'
      fullPath: '/nonhuman/chains'
      preLoaderRoute: typeof NonhumanChainsRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/nonhuman/dashboard': {
      id: '/nonhuman/dashboard'
      path: '/dashboard'
      fullPath: '/nonhuman/dashboard'
      preLoaderRoute: typeof NonhumanDashboardRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/nonhuman/mcp': {
      id: '/nonhuman/mcp'
      path: '/mcp'
      fullPath: '/nonhuman/mcp'
      preLoaderRoute: typeof NonhumanMcpRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/nonhuman/pay-per-call': {
      id: '/nonhuman/pay-per-call'
      path: '/pay-per-call'
      fullPath: '/nonhuman/pay-per-call'
      preLoaderRoute: typeof NonhumanPayPerCallRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/nonhuman/pricing': {
      id: '/nonhuman/pricing'
      path: '/pricing'
      fullPath: '/nonhuman/pricing'
      preLoaderRoute: typeof NonhumanPricingRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/nonhuman/wallets': {
      id: '/nonhuman/wallets'
      path: '/wallets'
      fullPath: '/nonhuman/wallets'
      preLoaderRoute: typeof NonhumanWalletsRouteImport
      parentRoute: typeof NonhumanRoute
    }
    '/api/public/openapi': {
      id: '/api/public/openapi'
      path: '/api/public/openapi'
      fullPath: '/api/public/openapi'
      preLoaderRoute: typeof ApiPublicOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/machine/$': {
      id: '/api/public/machine/$'
      path: '/api/public/machine/$'
      fullPath: '/api/public/machine/$'
      preLoaderRoute: typeof ApiPublicMachineSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HumanRouteChildren {
  HumanAndroidRoute: typeof HumanAndroidRoute
  HumanDeployRoute: typeof HumanDeployRoute
  HumanSetupRoute: typeof HumanSetupRoute
  HumanStudioRoute: typeof HumanStudioRoute
  HumanWalletRoute: typeof HumanWalletRoute
  HumanIndexRoute: typeof HumanIndexRoute
}

const HumanRouteChildren: HumanRouteChildren = {
  HumanAndroidRoute: HumanAndroidRoute,
  HumanDeployRoute: HumanDeployRoute,
  HumanSetupRoute: HumanSetupRoute,
  HumanStudioRoute: HumanStudioRoute,
  HumanWalletRoute: HumanWalletRoute,
  HumanIndexRoute: HumanIndexRoute,
}

const HumanRouteWithChildren = HumanRoute._addFileChildren(HumanRouteChildren)

interface NonhumanRouteChildren {
  NonhumanApiRoute: typeof NonhumanApiRoute
  NonhumanChainsRoute: typeof NonhumanChainsRoute
  NonhumanDashboardRoute: typeof NonhumanDashboardRoute
  NonhumanMcpRoute: typeof NonhumanMcpRoute
  NonhumanPayPerCallRoute: typeof NonhumanPayPerCallRoute
  NonhumanPricingRoute: typeof NonhumanPricingRoute
  NonhumanWalletsRoute: typeof NonhumanWalletsRoute
  NonhumanIndexRoute: typeof NonhumanIndexRoute
}

const NonhumanRouteChildren: NonhumanRouteChildren = {
  NonhumanApiRoute: NonhumanApiRoute,
  NonhumanChainsRoute: NonhumanChainsRoute,
  NonhumanDashboardRoute: NonhumanDashboardRoute,
  NonhumanMcpRoute: NonhumanMcpRoute,
  NonhumanPayPerCallRoute: NonhumanPayPerCallRoute,
  NonhumanPricingRoute: NonhumanPricingRoute,
  NonhumanWalletsRoute: NonhumanWalletsRoute,
  NonhumanIndexRoute: NonhumanIndexRoute,
}

const NonhumanRouteWithChildren = NonhumanRoute._addFileChildren(
  NonhumanRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertisingRoute: AdvertisingRoute,
  HumanRoute: HumanRouteWithChildren,
  NonhumanRoute: NonhumanRouteWithChildren,
  OwnerRoute: OwnerRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyChoicesRoute: PrivacyChoicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiHumanAiRoute: ApiHumanAiRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicOpenapiRoute: ApiPublicOpenapiRoute,
  ApiPublicMachineSplatRoute: ApiPublicMachineSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
