/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HumanRouteImport } from './routes/human'
import { Route as HumanIndexRouteImport } from './routes/human.index'
import { Route as HumanChainsRouteImport } from './routes/human.chains'
import { Route as HumanCustodyRouteImport } from './routes/human.custody'
import { Route as HumanDownloadRouteImport } from './routes/human.download'
import { Route as HumanPayRouteImport } from './routes/human.pay'
import { Route as HumanReleaseRouteImport } from './routes/human.release'
import { Route as HumanSecurityRouteImport } from './routes/human.security'
import { Route as HumanSetupRouteImport } from './routes/human.setup'
import { Route as HumanStudioRouteImport } from './routes/human.studio'

const HumanRoute = HumanRouteImport.update({
  id: '/human',
  path: '/human',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanIndexRoute = HumanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HumanRoute,
} as any)
const HumanChainsRoute = HumanChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => HumanRoute,
} as any)
const HumanCustodyRoute = HumanCustodyRouteImport.update({
  id: '/custody',
  path: '/custody',
  getParentRoute: () => HumanRoute,
} as any)
const HumanDownloadRoute = HumanDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => HumanRoute,
} as any)
const HumanPayRoute = HumanPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => HumanRoute,
} as any)
const HumanReleaseRoute = HumanReleaseRouteImport.update({
  id: '/release',
  path: '/release',
  getParentRoute: () => HumanRoute,
} as any)
const HumanSecurityRoute = HumanSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => HumanRoute,
} as any)
const HumanSetupRoute = HumanSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => HumanRoute,
} as any)
const HumanStudioRoute = HumanStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => HumanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/human': typeof HumanRouteWithChildren
  '/human/chains': typeof HumanChainsRoute
  '/human/custody': typeof HumanCustodyRoute
  '/human/download': typeof HumanDownloadRoute
  '/human/pay': typeof HumanPayRoute
  '/human/release': typeof HumanReleaseRoute
  '/human/security': typeof HumanSecurityRoute
  '/human/setup': typeof HumanSetupRoute
  '/human/studio': typeof HumanStudioRoute
  '/human/': typeof HumanIndexRoute
}
export interface FileRoutesByTo {
  '/human/chains': typeof HumanChainsRoute
  '/human/custody': typeof HumanCustodyRoute
  '/human/download': typeof HumanDownloadRoute
  '/human/pay': typeof HumanPayRoute
  '/human/release': typeof HumanReleaseRoute
  '/human/security': typeof HumanSecurityRoute
  '/human/setup': typeof HumanSetupRoute
  '/human/studio': typeof HumanStudioRoute
  '/human': typeof HumanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/human': typeof HumanRouteWithChildren
  '/human/chains': typeof HumanChainsRoute
  '/human/custody': typeof HumanCustodyRoute
  '/human/download': typeof HumanDownloadRoute
  '/human/pay': typeof HumanPayRoute
  '/human/release': typeof HumanReleaseRoute
  '/human/security': typeof HumanSecurityRoute
  '/human/setup': typeof HumanSetupRoute
  '/human/studio': typeof HumanStudioRoute
  '/human/': typeof HumanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/human'
    | '/human/chains'
    | '/human/custody'
    | '/human/download'
    | '/human/pay'
    | '/human/release'
    | '/human/security'
    | '/human/setup'
    | '/human/studio'
    | '/human/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/human/chains'
    | '/human/custody'
    | '/human/download'
    | '/human/pay'
    | '/human/release'
    | '/human/security'
    | '/human/setup'
    | '/human/studio'
    | '/human'
  id:
    | '__root__'
    | '/human'
    | '/human/chains'
    | '/human/custody'
    | '/human/download'
    | '/human/pay'
    | '/human/release'
    | '/human/security'
    | '/human/setup'
    | '/human/studio'
    | '/human/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HumanRoute: typeof HumanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/human': {
      id: '/human'
      path: '/human'
      fullPath: '/human'
      preLoaderRoute: typeof HumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human/': {
      id: '/human/'
      path: '/'
      fullPath: '/human/'
      preLoaderRoute: typeof HumanIndexRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/chains': {
      id: '/human/chains'
      path: '/chains'
      fullPath: '/human/chains'
      preLoaderRoute: typeof HumanChainsRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/custody': {
      id: '/human/custody'
      path: '/custody'
      fullPath: '/human/custody'
      preLoaderRoute: typeof HumanCustodyRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/download': {
      id: '/human/download'
      path: '/download'
      fullPath: '/human/download'
      preLoaderRoute: typeof HumanDownloadRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/pay': {
      id: '/human/pay'
      path: '/pay'
      fullPath: '/human/pay'
      preLoaderRoute: typeof HumanPayRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/release': {
      id: '/human/release'
      path: '/release'
      fullPath: '/human/release'
      preLoaderRoute: typeof HumanReleaseRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/security': {
      id: '/human/security'
      path: '/security'
      fullPath: '/human/security'
      preLoaderRoute: typeof HumanSecurityRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/setup': {
      id: '/human/setup'
      path: '/setup'
      fullPath: '/human/setup'
      preLoaderRoute: typeof HumanSetupRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/studio': {
      id: '/human/studio'
      path: '/studio'
      fullPath: '/human/studio'
      preLoaderRoute: typeof HumanStudioRouteImport
      parentRoute: typeof HumanRoute
    }
  }
}

interface HumanRouteChildren {
  HumanChainsRoute: typeof HumanChainsRoute
  HumanCustodyRoute: typeof HumanCustodyRoute
  HumanDownloadRoute: typeof HumanDownloadRoute
  HumanPayRoute: typeof HumanPayRoute
  HumanReleaseRoute: typeof HumanReleaseRoute
  HumanSecurityRoute: typeof HumanSecurityRoute
  HumanSetupRoute: typeof HumanSetupRoute
  HumanStudioRoute: typeof HumanStudioRoute
  HumanIndexRoute: typeof HumanIndexRoute
}

const HumanRouteChildren: HumanRouteChildren = {
  HumanChainsRoute: HumanChainsRoute,
  HumanCustodyRoute: HumanCustodyRoute,
  HumanDownloadRoute: HumanDownloadRoute,
  HumanPayRoute: HumanPayRoute,
  HumanReleaseRoute: HumanReleaseRoute,
  HumanSecurityRoute: HumanSecurityRoute,
  HumanSetupRoute: HumanSetupRoute,
  HumanStudioRoute: HumanStudioRoute,
  HumanIndexRoute: HumanIndexRoute,
}

const HumanRouteWithChildren = HumanRoute._addFileChildren(HumanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HumanRoute: HumanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
